### ISSUE TITLE
ABP Commercial translations

### ISSUE THREAD

**Issue by ebicoglu** [kgamalseif/hello-world#1]
hi kgamalseif,

I couldn't find your contact info and writing here...
We would like to have our ABP Commercial localizations translated into Arabic.
You made a good job on the free ABP translations.
Is it possible to help us also for the commercial side.
You can contact me to info@abp.io  My name's Alper.

**Comment by kgamalseif** [comment]
Hello Alper,

Thanks for your email,

OKAY, I can help. What next 🙂.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ebicoglu** [comment]
Hi,

Thanks for your response.
This is the translation file. I hope it's not too much for you.
You just fill the `target` fields.
When you finish, you can send it to me **alper.ebicoglu**[@] **volosoft**[.]**com**

[abp-translation.volo.ar-sa.zip](https://github.com/kgamalseif/hello-world/files/5434796/abp-translation.volo.ar-sa.zip)

**Comment by ebicoglu** [comment]
hi @kgamalseif  , did you have a chance to look at the Arabic translation file?

**Comment by kgamalseif** [comment]
Sorry , I was busy recently, started now, will revert back once finished 😊.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ebicoglu** [comment]
hi @kgamalseif,

let me know when you finish. if you finish it before Wednesday we will add to the next version.
